config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tweets#index"
  resources :tweets do
    resources :comments, only: [:destroy, :create]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :users, only:[:show, :edit, :update] do
    member do
      get :follows, :followers
    end
    member do
      get :favorites
    end
    resource :relationships, only: [:create, :destroy]
  end

  namespace :api, format: :json do
    namespace :v1 do
      post '/tweets/preview', to: 'tweets#preview'
    end
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many_attached :images

  validates :title, presence: true
  validates :text, presence: true, unless: :was_attached?
  validates :images, length: { minimum: 0, maximum: 5, message: 'は0枚以上5枚以下にしてください' }

  def was_attached?
    images.attached?
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search)
    if search != ''
      Tweet.where('text LIKE(?) OR title LIKE(?)', "%#{search}%", "%#{search}%")
    else
      Tweet.order('created_at DESC')
    end
  end
end

app/controllers/api/v1/tweets_controller.rb
module Api
  module V1
    class TweetsController < ApplicationController
      include MarkdownHelper # 先ほど作成したヘルパー

      # POST /api/v1/articles/preview
      def preview
        content = markdown(params[:text])
        render json: { content: content}
      end
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :update, :destroy, :show]
  before_action :authenticate_user!, except: [:index, :show, :search]

  def index
    @tweets = Tweet.includes(:user).page(params[:page]).per(4).order('created_at DESC')
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    return unless @tweet.user_id != current_user.id

    redirect_to root_path
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweet_path
    else
      render :edit
    end
  end

  def destroy
    @tweet.destroy
    redirect_to root_path
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def search
    @tweets = Tweet.search(params[:keyword]).order('created_at DESC')
  end

  private

  def tweet_params
    params.require(:tweet).permit(:title, :text, { images: [] }).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/edit.html.erb
<div class="cover-edit">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-3 mb-3">投稿編集</h1>
    </div>
    <div class="row justify-content-center">
      <%= form_with model: @tweet, url:"/tweets/#{@tweet.id}", id: 'new_tweet', local:true do |f| %>
      <div class="form-group">
        <label class="form-label">タイトル</label>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <label class="form-label">テキスト</label>
        <%= f.text_area :text, id: 'article_markdown_content',class: "form-control", placeholder:"マークダウン形式OK" %>
      </div>

      <div class="form-content">
        <div id="previews"></div>
        <label class="form-image"></label>
        <%= f.file_field :images, name: 'tweet[images][]', data: {index: 0}, class: "form-field" %>
      </div>

      <div class="code-block">
        <div class="code__block">
          <div class="preview__nav">Preview</div>
          <div class="markdown__space markdown" id="preview" ></div>
        </div>   
      </div>

      <%= f.submit '保存する', class: "btn btn-success" %><br>
      <%= link_to '投稿詳細ページへ', tweet_path(@tweet), class: "btn btn-dark mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="cover-index">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-3">投稿一覧</h1>
    </div>
    <div class=" justify-content-center ">
      <% @tweets.each do |tweet| %>
      <div class="one-post">
        <%= link_to tweet_path(tweet) do %>
        <p class="caption">
          <%= link_to tweet.title, tweet_path(tweet.id), class: :card__title%>

          <p class="caption">
          <article>
            <div class="toc"><%= toc(tweet.text).html_safe %>
            </div>
            <div class="markdown"><%= markdown(tweet.text).html_safe %>
             </div>
          </article>
          </p>
          <%= link_to image_tag(tweet.images[0], size: '300x200', class: :card__img ), tweet_path(tweet.id) if tweet.images.attached? %>
          <div class="postDate mt-1"><%= tweet.created_at.strftime("%Y年-%m月-%d日 %H時:%M分") %></div>
          <p class="caption"><%= "#{tweet.comments.count} コメント" %></p>
          <p class="caption"><%= "#{tweet.favorites.count} いいね" %></p>
          <%= link_to "by #{tweet.user.nickname}", user_path(tweet.user.id), class: :card__user %>
        <% end %>
      </div>
      <% end %>
    </div>
    <%= paginate @tweets %> 
  </div>
</div>

app/views/tweets/new.html.erb
<div class="cover-new">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-3 mb-3">新規投稿</h1>
    </div>
    <div class="row justify-content-center">
      <%= form_with model: @tweet, id: 'new_tweet', local: true do |f|%>
        <%= render 'shared/error_messages', model: f.object %>
      <div class="form-group">
        <label class="form-label">タイトル</label>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <label class="form-label">テキスト</label>
        <%= f.text_area :text, id: 'article_markdown_content',class: "form-control", placeholder:"マークダウン形式OK" %>
      </div>

      <div class="form-content">
        <div id="previews"></div>
        <label class="form-image"></label>
        <%= f.file_field :images, name: 'tweet[images][]', data: {index: 0}, class: "form-field" %>
      </div>

      <div class="code-block">
        <div class="code__block">
          <div class="preview__nav">Preview</div>
          <div class="markdown__space markdown" id="preview" ></div>
        </div>   
      </div>
      
      <%= f.submit '投稿する', class: "btn btn-success" %><br>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/search.html.erb
<div class="cover-index">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-3">検索結果</h1>
    </div>
    <div class="justify-content-center">
      <% @tweets.each do |tweet| %>
      <div class="one-post">
        <%= link_to tweet_path(tweet) do %>
        <p class="caption">
          <%= link_to tweet.title, tweet_path(tweet.id), class: :card__title%>
            <article>
              <div class="toc"><%= toc(tweet.text).html_safe %>
              </div>
              <div class="markdown"><%= markdown(tweet.text).html_safe %>
              </div>
            </article>
          <%= link_to image_tag(tweet.images[0], size: '300x200', class: :card__img ), tweet_path(tweet.id) if tweet.images.attached? %>
          <div class="postDate"><%= tweet.created_at.strftime("%Y年-%m月-%d日 %H時:%M分") %></div>
          <% if user_signed_in? %>
            <p class="caption">
            <% if tweet.favorited_by?(current_user) %>
            <%= link_to tweet_favorites_path(tweet.id), method: :delete do %>
              ♥<%= tweet.favorites.count %> いいね
            <% end %>
          <% else %>
            <%= link_to tweet_favorites_path(tweet), method: :post do %>
              ♡<%= tweet.favorites.count %> いいね
            <% end %>
          <% end %>
          <p class="caption"><%= "#{tweet.comments.count} コメント" %></p> 
        </p>
      <% end %>
          <%= link_to "by #{tweet.user.nickname}", user_path(tweet.user.id), class: :card__user %>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/show.html.erb
<div class="cover-index">
  <div class="container">
    <div class="container">
      <div class="row justify-content-center">
        <h1 class="font-weight-normal mt-3 ">投稿詳細</h1>
      </div>
      <div class="row justify-content-center d-block">
        <p class="caption">
          <%= link_to "#{@tweet.user.nickname}さんの投稿", user_path(@tweet.user.id), class: :prototype__user %>
        </p>
        
        <p class="caption"><%= @tweet.title %></p>
          <article>
            <div class="toc"><%= toc(@tweet.text).html_safe %>
            </div>
            <div class="markdown"><%= markdown(@tweet.text).html_safe %>
            </div>
          </article>
        <% if @tweet.images.attached? %>
          <%= image_tag @tweet.images[0], size: '300x200', class: "main-image" %><br> 
          <div class="other-images">
            <% @tweet.images[1..-1].each do |image| %>
              <div class="other-image">
                <%= image_tag image , size: '300x200'%>
              </div>
           <%end%>
          </div>
        <% end %>
        <div class="postDate mt-1"><%= @tweet.created_at.strftime("%Y年%m月%d日 %H時:%M分") %></div>
        <% if user_signed_in? && current_user.id == @tweet.user_id %>
          <%= link_to '編集する', edit_tweet_path(@tweet.id), class: "btn btn-info mr-3" %>
          <%= link_to '削除する', tweet_path(@tweet.id),method: :delete, "data-confirm"=>"本当に消しますか？", class: "btn btn-danger" %><br>
          <%= link_to '投稿一覧ページへ', tweets_path, class: "btn btn-dark mt-3 " %>
        <% end %>
      </div>
    </div>
    
    <div class="justify-content-center mt-3">
      <% if user_signed_in? && current_user.id != @tweet.user_id %>
        <p class="caption">
        <% if @tweet.favorited_by?(current_user) %>
          <%= link_to tweet_favorites_path(@tweet.id), method: :delete do %>
          ♥<%= @tweet.favorites.count %> いいね
          <% end %>
        <% else %>
          <%= link_to tweet_favorites_path(@tweet), method: :post do %>
            ♡<%= @tweet.favorites.count %> いいね
          <% end %>
        <% end %>
        </p>
      <% end %>
      <% if user_signed_in? && current_user.id == @tweet.user_id %>
        <p class="caption"><%= "#{@tweet.favorites.count} いいね" %></p>
      <% end %>
    </div>
    
    <div class="justify-content-center">
      <% if user_signed_in? %>
      <div class="comment-box">
        <%= form_with model: [@tweet, @comment], id: "comment-form" do |f| %>
          <%= f.text_area :content, :size=>"60x3",placeholder: "コメントする" %>
          <%= f.submit "送信", class: "btn btn-success mb-4" %>
        <% end %>
      </div>
      <% end %> 
    </div>

    <div class="justify-content-center">
      <div id="comments">
      <p>コメント件数：<%= @comments.count %></p>
        <% @tweet.comments.each do |comment| %>
          <div class="comments-index mb-2">
            <p class="user-info"><%= comment.user.nickname %></p>
            <div class="comment-content">
              <%= comment.content %><br>
              <%= comment.created_at.strftime("%Y年 %m月 %d日 %H時:%M分") %>
              <% if user_signed_in? && current_user.id == comment.user_id %>
              <div class="comment-delete">
                <%=link_to "削除", tweet_comment_path(comment.tweet.id, comment.id), method: :delete, class: "btn-sm btn-danger" %>
              </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>