config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tweets#index"
  resources :tweets do
    resources :comments, only: [:destroy, :create]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :users, only:[:show, :edit, :update] do
    member do
      get :follows, :followers
    end
    member do
      get :favorites
    end
    resource :relationships, only: [:create, :destroy]
  end

  namespace :api, format: :json do
    namespace :v1 do
      post '/tweets/preview', to: 'tweets#preview'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_many :tweets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  attachment :profile_image

  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy

  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def show
    @user = User.find(params[:id])
    @following_users = @user.following_user
    @follower_users = @user.follower_user
    @tweets = @user.tweets
    @tweets = @user.tweets.page(params[:page]).per(5).order('created_at DESC')
  end

  def follows
    user = User.find(params[:id])
    @users = user.following_user
  end

  def followers
    user = User.find(params[:id])
    @users = user.follower_user
  end

  def favorites
    @user = User.find(params[:id])
    favorites= Favorite.where(user_id: @user.id).order("created_at DESC").pluck(:tweet_id)
    @favorite_tweets = Tweet.find(favorites)
    @tweets = @user.tweets.page(params[:page]).per(5).order('created_at DESC')
  end
end

private

def user_params
  params.require(:user).permit(:nickname, :profile, :profile_image)
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="cover-user-edit">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-3 mb-3">プロフィール編集</h1>
    </div>
    <div class="row justify-content-center">
      <%= form_with model: @user, local:true do |f| %>
      <div class="form-group">
        <label class="form-label">名前</label>
        <%= f.text_field :nickname, autofocus: true, id:"inputName", placeholder:"名前", class: "form-control" %>
      </div>
      <div class="form-group">
        <label class="form-label">アイコン</label><br>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
      </div>
      <div class="form-group">
        <label class="form-label">自己紹介</label>
        <%= f.text_area :profile, class: "form-control" %><br>
      </div>
      <%= f.submit '保存する', class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

<%#%>

app/views/users/favorites.html.erb
<div class="cover-index">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-3">いいね一覧</h1>
    </div>
    <div class=" justify-content-center ">
    <% if @favorite_tweets.length == 0 %>
      <%= "「いいね」した投稿はありません" %>
    <% end %>
      <% @favorite_tweets.each do |tweet| %>
      <div class="one-post">
        <%= link_to tweet_path(tweet) do %>
        <p class="caption">
          <%= link_to tweet.title, tweet_path(tweet.id), class: :card__title%>

          <p class="caption">
          <article>
            <div class="toc"><%= toc(tweet.text).html_safe %>
            </div>
            <div class="markdown"><%= markdown(tweet.text).html_safe %>
             </div>
          </article>
          </p>
          <%= link_to image_tag(tweet.images[0], size: '300x200', class: :card__img ), tweet_path(tweet.id) if tweet.images.attached? %>
          <div class="postDate mt-1"><%= tweet.created_at.strftime("%Y年-%m月-%d日 %H時:%M分") %></div>
          <p class="caption"><%= "#{tweet.comments.count} コメント" %></p>
          <p class="caption"><%= "#{tweet.favorites.count} いいね" %></p>
          <%= link_to "by #{tweet.user.nickname}", user_path(tweet.user.id), class: :card__user %>
        <% end %>
      </div>
      <% end %>
    </div>
    <%= paginate @tweets %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="cover-user-index">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-3 mb-3">フォロワー</h1>
    </div>
    <div class="row justify-content-center">
      <% @users.each do |user| %>
      <div class="one-post card w-50">
        <%= link_to user_path(user) do %>
        <p class="nickname"><%= user.nickname %></p>
        <div class="image-image">
          <%= attachment_image_tag user, :profile_image, size: '100x100', fallback: "no_image.png", class: "mb-3 mt-3 ml-3 profile-img" %>
        </div>
        <p class="caption"><%= "#{user.tweets.count} 投稿" %></p>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/follows.html.erb
<div class="cover-user-index">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-3 mb-3">フォロー</h1>
    </div>
    <div class="row justify-content-center">
      <% @users.each do |user| %>
      <div class="one-post card w-50">
        <%= link_to user_path(user) do %>
        <p class="nickname"><%= user.nickname %></p>
        <div class="image-image">
          <%= attachment_image_tag user, :profile_image, size: '100x100', fallback: "no_image.png", class: "mb-3 mt-3 ml-3 profile-img" %>
        </div>
        <p class="caption"><%= "#{user.tweets.count} 投稿" %></p>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="cover-user-edit">
  <div class="container">
    <div class="row justify-content-center">
      <% if user_signed_in? && @user == current_user %>
      <h1 class="font-weight-normal mt-3 mb-3">マイページ</h1>
      <% else %>
      <h1 class="font-weight-normal mt-3 mb-3"><%= @user.nickname %>さんのページ</h1>
      <% end %>
    </div>
    <p class="d-flex justify-content-end">
      <% if user_signed_in? && @user == current_user %>
      <%= link_to "いいねした投稿", favorites_user_path(@user), class: "btn-sm btn-danger" %>
      <%= link_to "プロフィール編集", edit_user_path(@user), class: "btn-sm btn-success" %>
      <% end %>
      <% if user_signed_in? && current_user != @user %>
      <% if current_user.following?(@user) %>
      <%= link_to 'フォロー外す', user_relationships_path(@user.id), method: :delete, class: "btn-sm btn-danger" %>
      <% else %>
      <%= link_to 'フォローする', user_relationships_path(@user.id), method: :POST, class:"btn-sm btn-success" %>
      <% end %>
    </p>
    <% end %>
    <div class="ml-3 mb-3 card w-100">
      <div class="d-flex">
        <%= attachment_image_tag @user, :profile_image, size: '100x100', fallback: "no_image.png", class: "mb-3 mt-3 ml-3 profile-img" %>
        <% if @user.profile.present? %>
          <h4 class="ml-4 m-3"><%= safe_join(@user.profile.split("\n"),tag(:br)) %></h4>
        <% else %>
          <h4 class="ml-4 m-3"><%= @user.profile %></h4>
        <% end %>
      </div>
      <div class="d-flex">
        <%= link_to follows_user_path(@user) do %>
        <h6>フォロー<%= @following_users.count %></h6>
        <% end %>&nbsp;&nbsp;
        <%= link_to followers_user_path(@user) do %>
        <h6>フォロワー<%= @follower_users.count %></h6>
        <% end %>
      </div>
    </div>
    <div class="justify-content-center">
      <% @tweets.each do |tweet| %>
      <div class="one-post">
        <%= link_to tweet_path(tweet) do %>
        <%= link_to tweet.title, tweet_path(tweet.id), class: :card__title%>
        <p class="caption mb-0">
        <article>
          <div class="toc"><%= toc(tweet.text).html_safe %>
          </div>
          <div class="markdown"><%= markdown(tweet.text).html_safe %>
          </div>
        </article>
        </p>
        <%= link_to image_tag(tweet.images[0], size: '300x200', class: :card__img ), tweet_path(tweet.id) if tweet.images.attached?%>
        <div class="postDate mt-1"><%= tweet.created_at.strftime("%Y年-%m月-%d日 %H時:%M分") %></div>
        <p class="caption"><%= "#{tweet.comments.count} コメント" %></p>
        <p class="caption"><%= "#{tweet.favorites.count} いいね" %></p>
        <% end %>
      </div>
      <% end %>
    </div>
    <%= paginate @tweets %>
  </div>
</div>