config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tweets#index"
  resources :tweets do
    resources :comments, only: [:destroy, :create]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :users, only:[:show, :edit, :update] do
    member do
      get :follows, :followers
    end
    member do
      get :favorites
    end
    resource :relationships, only: [:create, :destroy]
  end

  namespace :api, format: :json do
    namespace :v1 do
      post '/tweets/preview', to: 'tweets#preview'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Memory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
            <%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
              <%= form.text_field :keyword, placeholder: "投稿を検索", class: "search-input" %>
              <%= form.submit "検索", class: "search-btn"  %>
             <% end %>
          </div>

          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "トップ", root_path, class: :nav__btn %>
              <%= link_to "マイページ", user_path(current_user.id), class: :nav__btn %>
              <%= link_to "新規投稿", new_tweet_path, class: :nav__btn %>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "トップ", root_path, class: :nav__btn %>
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <%= link_to image_tag("logo.png", class: :logo), root_path %>
    </footer>
  </body>
</html>